### PR TITLE
Add omero_web_system_uid

### PR DESCRIPTION
**Pull request by manics**
Closes https://github.com/openmicroscopy/ansible-role-omero-web/issues/6

### CODE REVIEW

**Comment by joshmoore** [comment]
Proposed as `1.0.3` or `1.1.0`? (And assuming along with gh-11)

**Comment by manics** [comment]
If there's no pressing need for it to have it's own release then include it in https://github.com/openmicroscopy/ansible-role-omero-web/pull/11#issuecomment-371430044

**Comment by joshmoore** [comment]
Where was the request originally coming from? @kennethgillen's list? Likely the timeline for gh-11 would then be important.

Either way, changes look sensible.

**Comment by manics** [comment]
You opened #6 whilst testing something.

**Comment by joshmoore** [comment]
Understood, so no rush (at least from my side).

**Comment by joshmoore** [comment]
After discussing with @manics @kennethgillen and @sbesson, merging for 2.0.0 though this may not immediately be bumped across our requirements files. (See 1.0.3 if a non-breaking change is needed)

**Pull request merged**
